
[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.virtualenv",
  "file",
  "gcc",
  "gnumake",
  "openssl",
  "libffi"
]

[phases.install]
cmds = [
  "cd Backend",
  "python3.11 -m venv .venv",
  ". .venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "cd Backend && . .venv/bin/activate && bash ../start.sh"

[variables]
PYTHONUNBUFFERED = "1"
