[phases.setup]
nixPkgs = [
  "python311",
  "file",
  "gcc",
  "openssl",
  "libffi",
]

[phases.install]
cmds = [
  "cd Backend",
  "python3.11 -m pip install --upgrade pip setuptools wheel",
  "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "cd Backend && bash ../start.sh"

[variables]
PYTHONUNBUFFERED = "1"
